name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Navigate to Frontend directory
        run: cd Frontend

      - name: Install Angular CLI and Dependencies
        run: |
          npm install -g @angular/cli
          npm install

      - name: Navigate back to root directory
        run: cd ..

      - name: Navigate to Backend directory
        run: cd Backend

      - name: Start MySQL server
        run: sudo systemctl start mysql

      - name: Set up MySQL
        run: |
          sudo apt-get update
          sudo apt-get install mysql-server -y
          sudo mysql -e "CREATE USER 'ems_user'@'localhost' IDENTIFIED BY 'password';"
          sudo mysql -e "GRANT ALL PRIVILEGES ON exam_management_system.* TO 'ems_user'@'localhost';"
          sudo mysql -e "FLUSH PRIVILEGES"
          sudo mysql -e "CREATE DATABASE IF NOT EXISTS exam_management_system;"
          

      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Spring Boot App
        run: ./mvnw package -DskipTests=true

      - name: Run Spring Boot Tests
        run: ./mvnw test
