name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Use Node.js version 14 to match with your project requirements

      - name: Navigate to Frontend directory
        run: cd Frontend

      - name: Install Angular CLI and Dependencies
        run: |
          npm install -g @angular/cli
          npm install

      - name: Navigate to root directory
        run: cd ..

      - name: Navigate to Backend directory
        run: cd Backend

      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Spring Boot App
        run: ./mvnw package -DskipTests=true

      - name: Run Spring Boot Tests
        run: ./mvnw test
